Update pubs list
monarch-initiative/monarch-ui pull request #402
Opened 2021-03-26 17:28 UTC by jen-martin

Addresses #400. Updates publications from Melissa, Chris and Peter's pubs on pubmed for 2019-2021.

2021-03-30 20:56 UTC, jmcmurry approved these changes
There are a couple probably missing (eg. LIRICAL / LOINC2HPO), but that shouldn't hold this batch up. Please merge.

2021-03-30 23:42 UTC, monicacecilia requested changes
Thank you for working on this, Jen. I've added a few comments for removal of some of these entries.

2021-03-31 20:46 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Gene Ontology Consortium. (2021) <b class="title">The Gene Ontology resource: enriching a GOld mine</b> <i>Nucleic Acids Res.</i> <b>49(D1)</b>:D325-D334. [<a target="__blank" href="ht
done

2021-03-31 20:47 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Rodríguez de Los Santos M, Rivalan M, David FS, Stumpf A, Pitsch J, Tsortouktzidis D, Velasquez LM, Voigt A, Schilling K, Mattei D, Long M, Vogt G, Knaus A, Fischer-Zirnsak B, Wittler
done

2021-03-31 20:47 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Vangay P, Burgin J, Johnston A, Beck KL, Berrios DC, Blumberg K, Canon S, Chain P, Chandonia JM, Christianson D, Costes SV, Damerow J, Duncan WD, Dundore-Arias JP, Fagnan K, Galazka JM
done

2021-03-31 20:47 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Alliance of Genome Resources Consortium. (2020) <b class="title">Alliance of Genome Resources Portal: unified model organism research platform</b>. <i>Nucleic Acids Res.</i> <b>48(D1)<
done

2021-03-31 20:47 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Arnaud E, Laporte MA, Kim S, Aubert C, Leonelli S, Miro B, Cooper L, Jaiswal P, Kruseman G, Shrestha R, Buttigieg PL, Mungall CJ, Pietragalla J, Agbona A, Muliro J, Detras J, Hualla V,
done

2021-03-31 20:47 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Mabee PM, Balhoff JP, Dahdul WM, Lapp H, Mungall CJ, Vision TJ. (2020) <b class="title">A Logical Model of Homology for Comparative Biology</b>. <i>Syst Biol.</i> <b>69(2)</b>:345-362.
done

2021-03-31 20:48 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Steinhaus R, Gonzalez T, Seelow D, Robinson PN. (2020) <b class="title">Pervasive and CpG-dependent promoter-like characteristics of transcribed enhancers</b>. <i>Nucleic Acids Res.</i
done

2021-03-31 20:48 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Touré V, Vercruysse S, Acencio ML, Lovering RC, Orchard S, Bradley G, Casals-Casas C, Chaouiya C, Del-Toro N, Flobak Å, Gaudet P, Hermjakob H, Hoyt CT, Licata L, Lægreid A, Mungall CJ,
done

2021-03-31 20:48 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Wood V, Carbon S, Harris MA, Lock A, Engel SR, Hill DP, Van Auken K, Attrill H, Feuermann M, Gaudet P, Lovering RC, Poux S, Rutherford KM, Mungall CJ. (2020) <b class="title">Term Matr
done

2021-03-31 20:48 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Wood-Charlson EM, Anubhav, Auberry D, Blanco H, Borkum MI, Corilo YE, Davenport KW, Deshpande S, Devarakonda R, Drake M, Duncan WD, Flynn MC, Hays D, Hu B, Huntemann M, Li PE, Lipton M
done

2021-03-31 20:48 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Bhushan R, Altinbas L, Jäger M, Zaradzki M, Lehmann D, Timmermann B, Clayton NP, Zhu Y, Kallenbach K, Kararigas G, Robinson PN. (2019) <b class="title">An integrative systems approach
done

2021-03-31 20:48 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Giglio M, Tauber R, Nadendla S, Munro J, Olley D, Ball S, Mitraka E, Schriml LM, Gaudet P, Hobbs ET, Erill I, Siegele DA, Hu JC, Mungall C, Chibucos MC. (2109) <b class="title">ECO, th
done

2021-03-31 20:48 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Hansen P, Ali S, Blau H, Danis D, Hecht J, Kornak U, Lupiáñez DG, Mundlos S, Steinhaus R, Robinson PN. (2019) <b class="title">GOPHER: Generator Of Probes for capture Hi-C Experiments
done

2021-03-31 20:49 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Hansen P, Gargano M, Hecht J, Ibn-Salem J, Karlebach G, Roehr JT, Robinson PN. (2019) <b class="title">Computational Processing and Quality Control of Hi-C, Capture Hi-C and Capture-C
done

2021-03-31 20:49 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Hsieh TC, Mensah MA, Pantel JT, Aguilar D, Bar O, Bayat A, Becerra-Solano L, Bentzen HB, Biskup S, Borisov O, Braaten O, Ciaccio C, Coutelier M, Cremer K, Danyel M, Daschkey S, Eden HD
done

2021-03-31 20:49 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Jia G, Li Y, Zhang H, Chattopadhyay I, Boeck Jensen A, Blair DR, Davis L, Robinson PN, Dahlén T, Brunak S, Benson M, Edgren G, Cox NJ, Gao X, Rzhetsky A. (2019) <b class="title">Estima
done

2021-03-31 20:49 UTC, jen-martin commented on src/views/Publications.md
> +            <p>Thomas PD, Hill DP, Mi H, Osumi-Sutherland D, Van Auken K, Carbon S, Balhoff JP, Albou LP, Good B, Gaudet P, Lewis SE, Mungall CJ. (2019) <b class="title">Gene Ontology Causal Activity
done

2021-04-01 00:25 UTC, monicacecilia approved these changes
This is wonderful, Jen. Thank you so much. @jen-martin 
:bowtie:  - we can merge now.

2021-04-01 14:35 UTC, merged